### ISSUE TITLE
Error: No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by AnthonyNahas** [tinesoft/generator-ngx-library#163]
I've just generated a new library, and facing the following issue in the demo app.

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Mac OS highSierra

### Generator Version
`"version": "6.0.0",`

but I guess that I have the latest version `6.0.1` maybe the version was not bumped in the last release

--> 

```
{
  "_from": "generator-ngx-library@latest",
  "_id": "generator-ngx-library@6.1.0",
  "_inBundle":  #false,
```
### Tools Version
`yo --version`:  `2.0.2`  
`node --version`:  `8.11.2`
`npm -v`:  `6.1.0`

### Targeted Angular version
V6

### Repro steps.
1. generate a new project
2. cd demo
3. npm i
4. ng serve

### The log given by the failure.
```
angular-material-extensions/test/demo $ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 13% building modules 30/44 modules 14 active …e_modules/@angular/forms/fesm5/forms.js✖ ｢wdm｣: Error: No module factory available for dependency type: ContextElementDependency
    at addDependency (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:407:12)
    at iterationOfArrayCallback (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:88:3)
    at addDependenciesBlock (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:423:5)
    at iterationOfArrayCallback (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:88:3)
    at addDependenciesBlock (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:426:5)
    at Compilation.processModuleDependencies (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:434:4)
    at afterBuild (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:556:15)
    at buildModule.err (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:600:11)
    at callback (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:358:35)
    at module.build.error (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:394:12)
    at resolveDependencies (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ContextModule.js:233:4)
    at ContextModule.result.resolveDependencies (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:476:25)
    at ContextModule.build (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ContextModule.js:158:8)
    at Compilation.buildModule (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:362:10)
    at factory.create (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:583:14)
    at hooks.afterResolve.callAsync (/Users/admin/Git/angular-material-extensions/test/demo/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ContextModuleFactory.js:150:16)

```

### Desired functionality.
should serve the demo app

### Mention any other details that might be useful.
webpack is duplicated.. because angular cli has a dependency to webpack too...

## SOLVED:
1. cd demo
2. npm rm webpack
3. rm -rf node_modules package-lock.json
4. npm i
5. ng serve

🎉 and it works

so you should remove webpack from the package.json from the demo directory

thank you

**Comment by tinesoft** [comment]
I agree the dependency may be redundant with cli's, but still, it shouldn't cause this error... (i tried installing demo deps with yarn and it worked fine, no error on `gulp serve:demo`...)

Anyway, i removed it
