### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by michaeldoye** [tinesoft/generator-ngx-library#171]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
MacOS (latest)

### Generator Version
6.2.1

### Tools Version

`yo --version`: 2.0.5
`node --version`: 8.12.0
`npm -v`: 6.4.1

### Targeted Angular version
7.2.8

### Repro steps.
run `gulp release --verions=x.x.x --ghToken=xxx`

### The log given by the failure.
```
Starting 'github-release'...

TypeError: Cannot read property 'replace' of undefined
    at ghGot (/Users/mdoye/Documents/GitHub/lib/node_modules/gh-got/index.js:32:58)
    at DestroyableTransform._transform (/Users/mdoye/Documents/GitHub/lib/node_modules/conventional-github-releaser/src/index.js:93:25)
    at DestroyableTransform.Transform._read (/Users/mdoye/Documents/GitHub/lib/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mdoye/Documents/GitHub/lib/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/mdoye/Documents/GitHub/lib/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/mdoye/Documents/GitHub/nlib/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/mdoye/Documents/GitHub/lib/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Readable.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Readable.emit (events.js:211:7)
```

### Desired functionality.
Should not fail I guess

### Mention any other details that might be useful.
Not sure what is causing this, but it gets to the `github-release` task and fails.

[here](https://github.com/michaeldoye/mat-markdown-editor) is the repo I am trying to run the release for.

**Comment by tinesoft** [comment]
Hi @michaeldoye
 
How did you solve your issue?
