### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Josee9988** [tinesoft/generator-ngx-library#175]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Linux joseumsi 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Generator Version

6.2.1

### Tools Version
Yo: 3.1.1
Node: 13.13.0
Npm: 6.14.4

### Targeted Angular version

6.x.x

### Repro steps.

1. Install al the dependencies 

`sudo npm I -g yo`
`sudo npm I -g gulp-cli`
`sudo npm I -g @angular/cli`
`sudo npm I -g generator-ngx-library`

2. Generate the library (here is when the problem occurs)

`yo ngx-library filter-pipe`

3. Fill al the 17 steps such as 'What is your name' .....

4. The error

![image](https://user-images.githubusercontent.com/38838976/80698185-63cb6880-8ada-11ea-84e1-4029402851f5.png)

### The log given by the failure.

```bash
Almost done (2/3). Running gulp npm-package to prepare your library package in dist/...
fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (/home/jose/Git/filter-pipe/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/jose/Git/filter-pipe/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/jose/Git/filter-pipe/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
ERROR!
[gulp npm-package] Failed to package the library...
```

Also if I run `gulp test` or `gulp build` it gives the same error output.

![image](https://user-images.githubusercontent.com/38838976/80698337-a55c1380-8ada-11ea-8e6a-9ae114f9de9a.png)

### Desired functionality.

I would like to know why it does not work.

### Mention any other details that might be useful.

It is the first time I use this tool and I was excited to start using it.

**Comment by Josee9988** [comment]
Update: It also happens with other versions of node

Retested with node 12.10 and npm 6.14.4

![image](https://user-images.githubusercontent.com/38838976/80705101-1b19ac80-8ae6-11ea-9383-7657f2e51a02.png)

Seems like there is any sort of problem with the node versions above 12 and gulp [StackOverflow](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node).

It doesn't seem your problem so I'll just close this issue. Have a nice day
