### ISSUE TITLE
Error when using @angular/material as peerDependencies

### ISSUE THREAD

**Issue by gwenaellarmet** [tinesoft/generator-ngx-library#84]
### Bug Report
```
- [X] bug report
- [ ] feature request
```

### OS and Version?

> Windows 7

### Tools Version

>yo --version
2.0.0

>node --version
v6.11.2

>npm -v
3.10.10

### Targeted Angular version
4.2.4

### Repro steps.

I generate a simple Angular Package with this generator and I have trouble integrating @angular/material as a dependancy. (with ng serve --preserve-symlinks).

I was able to use the generated library before I added @angular/material.
Does anyone has the same type of issues using this yeoman generator ?

for informations this is my package.json from my test app : 
```javascript
{
  "name": "packages-docs",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --preserve-symlinks",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/compiler": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.4.2",
    "typescript": "^2.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

The packages.json from my /dist library
```javascript
{
  "name": "game-of-thrones",
  "version": "0.0.1",
  "description": "Angular library built with ❤ using ngx-library yeoman generator.",
  "keywords": [
    "ng",
    "angular",
    "library"
  ],
  "author": {
    "name": "Gwenael LARMET",
    "url": "http://github.com/gwenaellarmet"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/gwenaellarmet/game-of-thrones.git"
  },
  "license": "MIT",
  "bugs": {
    "url": "http://github.com/gwenaellarmet/game-of-thrones/issues"
  },
  "homepage": "http://github.com/gwenaellarmet/game-of-thrones",
  "main": "bundles/game-of-thrones.umd.js",
  "module": "game-of-thrones.js",
  "es2015": "game-of-thrones.es5.js",
  "typings": "game-of-thrones.d.ts",
  "peerDependencies": {
    "@angular/common": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/material": "^2.0.0-beta.10"
  }
}
```

I change the gulpfile generated by generator-ngx-library in order to add my dependencies : 
(version of rollup : 0.45.2)

```javascript
 const globals = {
      // Angular dependencies
      'typescript'         : 'ts',
      '@angular/core'      : 'ng.core',
      '@angular/common'    : 'ng.common',

      '@angular/animations': 'ng.animations',
      '@angular/cdk'       : 'ng.cdk',
      '@angular/material'  : 'ng.material'
    };
```

### The log given by the failure.

Using the cli to launch my test project, I have this warning :

```
WARNING in ./node_modules/game-of-thrones/game-of-thrones.js
2405:51-57 "export 'ɵmerge' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\dependencies
\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\dependencie
s\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\Compilatio
n.js:694:24)
    at Compilation.finish (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\Compiler.js:512:17)
    at E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (E:\Utilisateurs\SI069350\Documents\WorkSpace\Projects\packages-docs\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

In my Chrome console, I have this error :

![error](https://user-images.githubusercontent.com/6586707/30685215-7960ead6-9eb4-11e7-955d-1cd477328ddb.png)

**Comment by tinesoft** [comment]
Hi @gwenaellarmet 

Could you provide a minimal repro repository?

**Comment by gwenaellarmet** [comment]
Sure thing,

Here you have the package repo : https://github.com/gwenaellarmet/game-of-thrones
And here is where I try to integrate it : https://github.com/gwenaellarmet/testing-packages

**Comment by tinesoft** [comment]
Hi @gwenaellarmet 

I submitted  https://github.com/gwenaellarmet/game-of-thrones/pull/1 on your repo, with detailed
explanation on how to properly use the generator.


Please have a look, a feel free to re-open if still having issue.


Cheers
